services:
  - type: web
    name: backend
    env: node
    buildCommand: cd apps/be-challenge-test && npm install && npm run build
    startCommand: cd apps/be-challenge-test && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_CONNECTION_URI
        sync: true
      - key: DB_NAME
      - sync: true

  - type: web
    name: frontend
    env: static
    buildCommand: cd apps/fe-challenge-test && npm install && npm run build
    staticPublishPath: ./apps/fe-challenge-test/dist/fe-challenge-test
    routes:
      - type: rewrite
        source: /api
        destination: https://${RENDER_EXTERNAL_HOSTNAME}-backend.onrender.com/api
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: ROOT_API_URL
        sync: true
