services:
  - type: web
    name: backend
    env: node
    buildCommand: cd apps/be-challenge-test && yarn install && yarn add @nestjs/cli && yarn run build
    startCommand: cd apps/be-challenge-test && yarn run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_CONNECTION_URI
        sync: false
      - key: DB_NAME
        sync: false

  - type: web
    name: frontend
    env: node
    buildCommand: |
      cd apps/fe-challenge-test
      yarn install
      yarn global add @angular/cli 
      ng build --configuration production
    startCommand: cd apps/fe-challenge-test && npx serve -s dist/fe-challenge-test
    envVars:
      - key: NODE_ENV
        value: production
      - key: ROOT_API_URL
        value: https://${RENDER_EXTERNAL_HOSTNAME}-backend.onrender.com
