services:
  - type: web
    name: backend
    env: node
    buildCommand: cd apps/be-challenge-test && yarn install && yarn add @nestjs/cli && yarn run build
    startCommand: cd apps/be-challenge-test && yarn global add @angular/cli && yarn run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_CONNECTION_URI
        sync: false
      - key: DB_NAME
        sync: false

  - type: web
    name: frontend
    env: node
    buildCommand: |
      cd apps/fe-challenge-test
      yarn install
      yarn add @angular/cli
      export PATH="$PATH:$(pwd)/node_modules/.bin"
      ng build --configuration production
    staticPublishPath: ./apps/fe-challenge-test/dist/fe-challenge-test
    routes:
      - type: rewrite
        source: /api
        destination: https://${RENDER_EXTERNAL_HOSTNAME}-backend.onrender.com/api
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://${RENDER_EXTERNAL_HOSTNAME}-backend.onrender.com
